### ISSUE TITLE
Update project: Scalafix license

### ISSUE THREAD

**Issue by sideeffffect** [stkeky/best-of-scala#54]
**Update details:**

- Project Name: Scalafix

Scalafix is licensed under BSD 3-Clause Lincense https://github.com/scalacenter/scalafix/blob/main/LICENSE.md

Yet it is described here as "Unlicensed"
![image](https://github.com/stkeky/best-of-scala/assets/9019485/66248c37-9b04-4bd0-99e6-ee9fcabfa2cb)

**Additional context:**

**Comment by stkeky** [comment]
Hey @sideeffffect, thanks for reaching out.

I checked it, and yes, but since it is obtained from Github directly, Github itself doesn't recognize it as BSD-3 it just points to the license file.

![Screenshot (10)](https://github.com/stkeky/best-of-scala/assets/16312404/61f0630e-eb5d-4db6-84c9-9029a23b09e4)

I can probably override it, but it's probably better for `scalafix` to adapt it so that Github also recognizes it correctly.

**Comment by sideeffffect** [comment]
The README may need to be refreshed, the Scalafix project have updated their license file already and it is properly recognized by GitHub.

**Comment by stkeky** [comment]
@sideeffffect Thank you for updating it. Everything should be fine with the latest release.
